@startuml
!pragma teoz true

skinparam sequenceGroupHeaderFontStyle plain
skinparam sequence {
  LifeLineBorderColor #0a14a4ff
  LifeLineBorderThickness 2
  LifeLineBackgroundColor #116599ff
  ParticipantBorderColor #A0B4C8
  ParticipantBackgroundColor #A0B4C8
  GroupHeaderFontSize 10
  GroupBorderColor #f00817ff
  GroupBorderThickness 0.5
}

skinparam sequenceGroupFontSize 10
skinparam SequenceGroupFontStyle plain
skinparam sequenceGroupHeaderFontSize 10


skinparam Arrow {
  color #0e0f0fff
  thickness 1
  fontColor #5E6C84
}

skinparam Note {
  backgroundColor #E6F0FF
  borderColor #A4C6FF
  fontColor #1F2328
  roundCorner 6
}

participant "用户" as User
participant "PayIn" as Payin
participant "风控(RISK)" as Risk
participant "合规(COMPLIANCE)" as Compliance
participant "支付渠道(CHANNEL)" as Channel
participant "技术、运营" as Ops

autonumber

activate User
User -> Payin: 提交退款请求
deactivate User

activate Payin
Payin -> Payin: 初始化退款单(status=INIT)

group 风控准入审核
  Payin -> Payin: (status=WAIT_RISK_AUDIT)
  Payin -> Risk++: 发起风险评估
  Payin -> Payin: 等待风控审核结果(status=RISK_AUDIT_ING)

  alt 审核通过
    Risk --> Payin: <color:green>通过</color>审批通过,流转到合规处理 (status=WAIT_COMPLIANCE_CONFIRM)
  else 审核失败
    Risk --> Payin: <color:red>风控驳回</color> (status=RISK_REFUSE, <color:red>refund_status=FAIL) 风控驳回,退款失败
    User++
    Payin --> User--: <color:red>退款失败</color>
    User--
  end
    Risk--
end
deactivate Payin

||40||

group 合规性核验
  Payin -> Compliance++: 提交凭证/确认来源

  alt 场景 A：第三方机构/企业
    Compliance --> Payin++: (status=WAIT_CONFIRM_SENDER_INFO 待确认实际付款人信息)
    Compliance--
    Payin --> User++: 通知上传凭证
    User --[#blue]> Payin: 用户上传
    User--

    loop 补件审核循环
      Payin -> Compliance++: 提交核验
      alt 失败
        Compliance --> Payin: <color:red>驳回</color>
        Payin --> User++: <color:red>重新上传</color>
        User --[#blue]> Payin: 再次提交
        User--
      else 通过
        Compliance --> Payin: <color:green>明确付款人</color>(status=COMPLIANCE_CONFIRM) 合规确认通过
      end
    end
  else 场景 B：个人直退
    Compliance --> Payin: <color:green>校验通过</color> (status=COMPLIANCE_CONFIRM) 合规确认通过
  end
  Compliance--
  Payin--
end

||40||

group 渠道下发执行
  loop 渠道重试
    Payin -> Payin++: (status=CHANNEL_PROCESS)
    Payin -> Channel++: 调用退款接口

    alt 成功
      Channel --> Payin: <color:green>SUCCESS</color>
      User++
      Payin --> User: <color:green>成功通知</color>
      User--
    else 失败
      Channel --> Payin: <color:red>FAILED</color>

      alt 内部错误
        Payin -> Ops++: 技术处理
        Ops --> Payin: <color:green>修复完成</color>
        Ops--
      else 外部错误
        alt 明确错误码
             Payin -> User++: (status=WAIT_COMPLETE_INFO) 待用户提交收款账户信息
             User --[#blue]> Payin: 提交收款账户信息
             User--
             Payin-> Channel: 重新调用退款接口
             Channel--
        else 未知错误码
            Payin --> Ops: 和渠道确认处理方案
            Ops++
            Ops--
            User--
        end

      end
    end
    Channel--
  end
  Payin--
end

deactivate Payin

@enduml